### ISSUE TITLE
Understand Python 3.5 Failures

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#103]
In [Python 3.5 _only_](https://travis-ci.org/diana-hep/pyhf/builds/363848182) the result of resetting the TensorFlow backend graph and session after each run identified in Issue #102 results in a failure of tests. This can be seen in the [Python 3.5 output in Travis CI build #333.2](https://travis-ci.org/diana-hep/pyhf/jobs/363848184) for PR #92.

A brief excerpt from the trace follows:
```python-traceback
tests/test_benchmark.py ...FFF...                                        [ 29%]
tests/test_import.py F                                                   [ 32%]
tests/test_notebooks.py .                                                [ 35%]
tests/test_optim.py ...                                                  [ 45%]
tests/test_pdf.py FFFFFFF                                                [ 67%]
tests/test_tensor.py ...                                                 [ 77%]
tests/test_validation.py FFFFF.F                                         [100%]
=================================== FAILURES ===================================
_____________________ test_runOnePoint[tensorflow-10_bins] _____________________
self = <tensorflow.python.client.session.Session object at 0x7f06b412c160>
fn = <function BaseSession._do_run.<locals>._run_fn at 0x7f0699f82ea0>
args = ({b'concat:0': array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], dtype=float32)}, [b'strided_slice_8:0'], [], None, None)
message = 'Input is not invertible.\n\t [[Node: MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_1)]]'
m = <_sre.SRE_Match object; span=(27, 50), match='[[Node: MatrixInverse ='>
    def _do_call(self, fn, *args):
      try:
>       return fn(*args)
../../../miniconda/envs/test-environment/lib/python3.5/site-packages/tensorflow/python/client/session.py:1327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```
As this does not occur for Python 3.6 it would be worth understanding why. Additionally, asking if it is worth supporting Python 3.5 given that most Python 3 users are following releases and have Python 3.6 installed.

**Comment by matthewfeickert** [comment]
This seems to have been the result of undefined behavior as outlined in the [`tf.reset_default_graph` docs](https://www.tensorflow.org/api_docs/python/tf/reset_default_graph):
>The default graph is a property of the current thread. This function applies only to the current thread. Calling this function while a `tf.Session` or `tf.InteractiveSession` is active will result in undefined behavior. Using any previously created `tf.Operation` or `tf.Tensor` objects after calling this function will result in undefined behavior.

This undefined behavior seems to have been caused by clearing the graph after execution, instead of before. This is now being mitigated against by doing something along the lines of
```python
    if isinstance(pyhf.tensorlib, tensorflow_backend):
        # Reset the TensorFlow graph and session for each run
        tf.reset_default_graph()
        pyhf.tensorlib.session = tf.Session()

    return pyhf.runOnePoint(1.0, data, pdf,
                            pdf.config.suggested_init(),
                            pdf.config.suggested_bounds())
```
where the graph is explicitly reset immediately prior to building a new one and execution.

As this seems to have been a undefined behavior problem, and not something specific to Python 3.5 this will get closed for now.

**Comment by matthewfeickert** [comment]
This actually seems to be related to issues in Travis CI with the [`push` build and `pr` build](https://docs.travis-ci.com/user/pull-requests/#%E2%80%98Double-builds%E2%80%99-on-pull-requests), where the `push` build fails but the `pr` build passes, or vice versa. This needs followup.

**Comment by matthewfeickert** [comment]
In situations where either the `push` build passes and the `pr` build fails, or the `pr` build passes and the `push` build fails it seems that manually restarting the failed build will cause the build to pass. This seems strange.
Examples:
- Travis CI [`push` builds](https://travis-ci.org/diana-hep/pyhf/builds) 342, 344, 346
- corresponding Travis [`pr` builds](https://travis-ci.org/diana-hep/pyhf/pull_requests) 343, 345, 347

This isn't a pyhf issue, so closing, but @lukasheinrich if you have had experience with these Travis build issues before any info would be helpful for the future. For context, before doing a rebase the `pr` build passed and the `push` build failed, then after doing a rebase against master the `push` build passed while the `pr` build failed. A manual restart of the `pr` build then caused it to pass. :?

**Comment by matthewfeickert** [comment]
c.f. Travis CI builds [362](https://travis-ci.org/diana-hep/pyhf/builds/365864328) (failing) and [363](https://travis-ci.org/diana-hep/pyhf/builds/365872621) (passing) for example of the _same_ code failing in Python 3.5 in one instance and passing in the other.

**Comment by lukasheinrich** [comment]
I have some hunch that in yadgae it was something about relying on dict key order which is undefined behavior. Can't find it right now in yadage, but could be interesting to look at

**Comment by matthewfeickert** [comment]
How important is it that we actually support Python 3.5, instead of just being Python 2.7 ([until 2020](https://pythonclock.org/) :wink:) and Python 3.6?

**Comment by lukasheinrich** [comment]
yeah not married to it

**Comment by matthewfeickert** [comment]
Okay, then I'm removing testing support in PR #112.
