### ISSUE TITLE
Define API pdf sampling via e.g. probabilistic frameworks like edward

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#109]
# Description

We want to have the ability to sample from the pdf. A nice way to do this is via native probprog frameworks like Edward that hook in somewhat natively into tensor backends (not sure if there are similar projects for PyTorch, MXnet @cranmer ?). Not clear to me yet how to do this cleanly across numpy/TF/PyTorch/MXnet

For reference I added this super-simplified notebook to show how to sample sth like

```
p(n,a | alpha) = Pois(n |nu(alpha) ) * Gaus(a | alpha)
```
which is the core structure of HF right now

https://github.com/diana-hep/pyhf/blob/master/examples/experiments/edwardpyhf.ipynb

**Comment by lukasheinrich** [comment]
ok so I think pyro is the right analogue to edward for pytorch. MXnet has some distributions etc, but haven't found a 'framework' yes (but maybe that's not strictly needed

**Comment by matthewfeickert** [comment]
Closed through PR #558
