### ISSUE TITLE
Make sure pipenv-based development workflow works

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#116]
# Description

We support a number of extras like the various tensorbackends, but as far as I know none of them are mutually exclusive and all of them are needed for running the unit tests.

We should therefore make sure `pip install -e[develop]` installs all necessary packages to run the tests. I think also pytest-benchmark is missing (@kratsg mentioned that)

**Comment by lukasheinrich** [comment]
hm -- maybe this is an issue with my local installation since that's exactly what we do in travis.

**Comment by matthewfeickert** [comment]
Hm, this seems odd as [`pytest-benchmark[histogram]` is in the `develop`list](https://github.com/diana-hep/pyhf/blob/master/setup.py#L29). I agree that we should make sure that everything is installed though with it.

**Comment by matthewfeickert** [comment]
We can also see from [Travis Build 366](https://travis-ci.org/diana-hep/pyhf/builds/365891896) that the benchmarks are getting run, so it is being setup correctly by `pip install -e .[develop]` in the CI.

**Comment by lukasheinrich** [comment]
@matthewfeickert I think the issue might be that we manually upgrade pytest in the travis file. If we need a specific version probably `pip install` should pick up the right one

concretely what happens for me is that with pipenv

```
pipenv install -e[develop]
```

it still picks up a pytest outside of the pipenv, and that pytest wil not be able to import dependencies installed in the virtualenv

**Comment by matthewfeickert** [comment]
Ah okay. Sorry, I haven't been using pipenv so I haven't noticed this. Let me setup a new environment with it and see what is the minimum package versions to make things work.

**Comment by lukasheinrich** [comment]
closing this can't even reproduce this locally :-p

**Comment by matthewfeickert** [comment]
Ah okay, so all is working well then?
