### ISSUE TITLE
Back-end submodule structuring should be less convoluted?

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#121]
# Description

The current way of importing backends is a little redundant:

```python
from pyhf.tensor.numpy_backend import numpy_backend
from pyhf.tensor.pytorch_backend import pytorch_backend
from pyhf.tensor.tensorflow_backend import tensorflow_backend
from pyhf.tensor.mxnet_backend import mxnet_backend
```

Something more pythonic would be

```python
from pyhf.tensor.backends import numpy_backend, pytorch_backend, tensorflow_backend, mxnet_backend
```

Or is there something technically difficult about doing it this way?

**Comment by lukasheinrich** [comment]
I'd lke to keep all of these backend in different files, but probably with `__init__.py` and `__all__` we could get to the import semantic you lay out

**Comment by matthewfeickert** [comment]
I think this can be closed now. @kratsg please reopen if I'm wrong.
