### ISSUE TITLE
test_backend_consistency not resetting to default backend if test fails unexpectedly

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#125]
# Description

A cascading error is observed when test_backend_consistency fails, which keeps the backend as tensorflow and causes all the other tests to erroneously fail.

    
<img width="1550" alt="screenshot 2018-04-15 20 45 50" src="https://user-images.githubusercontent.com/761483/38786764-92380ebc-40ef-11e8-921c-fc20a2d96578.png">

Easy to reproduce, run `pytest` and see `test_pdf.py` fail. Run `pytest tests/test_pdf.py` and see that it's fine (as in screenshot).

**Comment by matthewfeickert** [comment]
@kratsg Does `test_backend_consistency.py` fail when run by itself?
