### ISSUE TITLE
Refactor shared modifiers from hfpdf to modifier code

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#130]
# Description

Modifiers alone should contain the logic for whether they are singletons or not (based on the name used to initialize the modifier). Specifically, I want to switch to using singletons which might be more elegant here (http://python-3-patterns-idioms-test.readthedocs.io/en/latest/Singleton.html) as this removes the actual logic of knowing which modifier is shared and which is not, from `hfpdf` as it should not care -- this is modifier-specific behavior, no? I think something like the `Borg` version is the most elegant via something like

```
class Modifier(object):
  pass

class UnsharedModifier(Modifier):
  def __init__(self, name):
      pass

class SharedModifier(Modifier):
  _shared_state = {}
  def __init__(self, name):
    self.__dict__ = _shared_state.setdefault(name, {}).get(name)

class ShapeSys(UnsharedModifier):
  def __init__(self, name):
    super(self.__class__, self).__init__(name)
    self.name = name

class HistoSys(SharedModifier):
  def __init__(self, name):
    super(self.__class__, self).__init__(name)
    self.name = name
```

then the modifiers, themselves, encode whether or not they're shared -- and the `hfpdf` code doesn't care at all [and it shouldn't].

# Relevant Issues and Pull Requests

Raised during the refactor in #120 . See #129 for the testing of such a thing.

**Comment by lukasheinrich** [comment]
I don't think we want literal singletons. E.g. we can easily imaging that we have some script that handles many different likelihood instances (say for multiple analyses), so we should not enforce singletons on the python object level. Shared modifieres are single-instance only within scope of a given `hfpdf`

**Comment by kratsg** [comment]
> I don't think we want literal singletons. E.g. we can easily imagine that we have some script that handles many different likelihood instances (say for multiple analyses), so we should not enforce singletons on the python object level. Shared modifieres are single-instance only within scope of a given hfpdf

Good point. How do you deal with someone defining a custom modifier? I suppose you want to add an attribute, similar to `is_constrained` that is `is_shared` to specify that the given modifier is meant to be shared?

**Comment by kratsg** [comment]
I'm using `is_shared` and in #120.
