### ISSUE TITLE
figure out why we do `CLb / CLsb`

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#140]
# Description

we have this snippet:

```python
from scipy.stats import norm
def pvals_from_teststat(sqrtqmu_v, sqrtqmuA_v):
    CLsb = 1 - norm.cdf(sqrtqmu_v)
    CLb = norm.cdf(sqrtqmuA_v - sqrtqmu_v)
    CLs = CLb / CLsb
    return CLsb, CLb, CLs
```

as @matthewfeickert correctly observed this seems off at first sight. But I seem to remember there was a specific reason I did it this way (perhaps while keeping around wrong variable names) 

i think it has something to do with this line in ROOT

```c++
 virtual Double_t CLb() const { return !fBackgroundIsAlt ? NullPValue() : AlternatePValue(); }
```

https://root.cern.ch/doc/v606/HypoTestResult_8h_source.html#l00138

**Comment by lukasheinrich** [comment]
I think the issue is that in ROOT, it's setup genericall as a Hypothesis test between a Null Hypothesis and an Alternate Hypothesis, one will be "background-only" while the other one will not, and this assignment is not fixed. It's a choice set by the HypoTestInverter, and relates to whether we do an exclusion or a discovery fit

https://root.cern.ch/doc/v608/HypoTestInverter_8cxx_source.html#l00500

**Comment by matthewfeickert** [comment]
From PR #141:
> Arguably we should just return CLs instead of 1/CLs, but I didn't want to change all the other pieces that might rely on the output of runOnePoint

@lukasheinrich Are there any objections to in another PR going through and checking all of this and moving to the CLs return structure?

**Comment by lukasheinrich** [comment]
no, not at all. I think that's what we should do

**Comment by matthewfeickert** [comment]
Unless someone beats me to it I'll work on this once I catch up on sleep.
