### ISSUE TITLE
add tensor clipping to shared API of tensorlib

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#147]
# Description

in order to get #95 it would be useful to have support in the tensor libraries for tensor clipping in order to nicely implement 

```
    if -1e-6 < qmu < 0:
        log.warning('WARNING: qmu negative: %s', qmu)
        return 0.0
```

in a more tensor-native way. all backends support this

http://pytorch.org/docs/master/torch.html?#torch.clamp
https://www.tensorflow.org/api_docs/python/tf/clip_by_value
https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html
https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.clip

so this should be an easy one. I would suggest `clip` as the name

**Comment by matthewfeickert** [comment]
You're thinking this, yes?
```python
    if -1e-6 < qmu < 0:
        log.warning('WARNING: qmu negative: %s', qmu)
        qmu = tensorlib.tolist(tensorlib.clip(qmu, 0, max=None))[0]
    return qmu
```

**Comment by lukasheinrich** [comment]
no with clip we don't need the if clause anymore.. i originally had a lower bound to make it fail hard if stuff is obviously wrong (mathematically it should be exactly > 0, but does to some rounding I guess i can turn out slightly < 0, but we want to take a sqrt later, so that's why I added it

**Comment by kratsg** [comment]
Hrmm, why not instead of *always* clipping, only clip on the try/except around the `sqrt`? Clipping does require a check in each element of the array, but this might be a pointless optimization.

**Comment by matthewfeickert** [comment]
I had left the `if -1e-6 < qmu < 0:` in as I thought there might be some marginal utility in still getting warning information that `qmu` had been evaluated as negative. However, that has now been removed to just leave the clipping
```python
    qmu = tensorlib.tolist(tensorlib.clip([qmu], 0, max=None))[0]
    return qmu
```
I can move the clipping, though I would assume that this isn't killing us at the moment.

**Comment by matthewfeickert** [comment]
I moved the clipping to `runOnePoint` in 1994fc7

**Comment by kratsg** [comment]
> though I would assume that this isn't killing us at the moment.

I would argue that creating a temporary object to just return it is probably optimized out in pypy and similar JIT compilers. For general purpose use, it might be useful to just do `return tensorlib.tolist(tensorlib.clip([qmu], 0, max=None))[0]`. Is there a reason for the `[0]` here?

Otherwise, I'm ok with the second suggestion as the clipping probably becomes streamlined now.

**Comment by matthewfeickert** [comment]
Oh, I just changed it. Do you want me to change it back?

The `[0]` was just because I was trying to make a style choice with passing in `[qmu]` instead of `qmu`, but as you pointed out that looks kinda weird so that also got changed in 1994fc7.

**Comment by kratsg** [comment]
> The [0] was just because I was trying to make a style choice with passing in [qmu] instead of qmu, but as you pointed out that looks kinda weird so that also got changed in 1994fc7.

debatable here. Remember that there's some underlying conversion done going from a tensorlib tensor to the python scalars -- and doing this a lot of times might slow things down. But I'm not sure, @lukasheinrich ?

**Comment by matthewfeickert** [comment]
@kratsg Sorry I was leaving for the bus when I wrote that, so I think I misunderstood what you meant. I’ve moved the clipping into a try/except statement in `runOnePoint` like you suggested. I am correct that you think this is okay now?

**Comment by kratsg** [comment]
Yeah, so I think the try/except is the most pythonic and will give us slight speed ups in situations where we don't have any negative values to clip. In the cases we do, we will (rightfully) warn the user that things are being clipped.
