### ISSUE TITLE
XML ROOT Export

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#170]
# Description

Given that we observe that some models still scale better in ROOT, it's reasonable to have some an companion tools to `readxml`, namely `writexml` that writes XML + ROOT files corresponding to a model given as JSON.

**Comment by lukasheinrich** [comment]
@kratsg this might be useful to comput published hf JSON in ROOT (e..g MBJ)

**Comment by kratsg** [comment]
Yeah, this is going to be much harder to build unfortunately, but it's still possible. It's a lower priority for now.

**Comment by kratsg** [comment]
uproot 3.0 is released that allows us to write XML+ROOT out now!
