### ISSUE TITLE
Add binderexample/StatisticalAnalysis.ipynb to docs examples

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#173]
At the moment the Binder example notebook `binderexample/StatisticalAnalysis.ipynb` is not being included in the build of the docs. Lukas has put some really nice examples in there and it would be nice to have this in the docs in the even that people don't check out the Binder.

# Relevant Issues and Pull Requests

This is also somewhat relevant to Issue #168

**Comment by kratsg** [comment]
https://github.com/diana-hep/pyhf/blob/master/docs/conf.py#L94-L97

**Comment by matthewfeickert** [comment]
Sure, I guess I should have said "We currently intentionally ignore these. Is there a reason we do so?"

**Comment by kratsg** [comment]
yeah, wasn't sure why we had two diff directories. But nothing in binderexample is tested.

**Comment by matthewfeickert** [comment]
I assume it was just to make it really clear what extra stuff was just for the Binder? Okay, good to know there isn't a technical case to ignore. :+1:

**Comment by lukasheinrich** [comment]
The only reason I put it in a separate dir is because there were a couple of additional files (the gif, the xml and the root file) that needed to be distributed together with the notebook, so I thought it was best to group it all together in a dir
