### ISSUE TITLE
Add pyhf talks section to README

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#178]
Now that [Lukas has given the first talk on pyhf](https://indico.cern.ch/event/702612/contributions/2958658/) :+1:  it might be nice to have a "Talks and Presentations" section towards the bottom of the README where we link to this and future talks.

Example:
[
## Presentations on pyhf
- Lukas Heinrich, "[pyhf: A standalone HistFactory Implementation](https://indico.cern.ch/event/702612/contributions/2958658/)", (Re)interpreting the results of new physics searches at the LHC Workshop, CERN, May 15, 2018

]

Thoughts?

**Comment by lukasheinrich** [comment]
absolutely!

**Comment by kratsg** [comment]
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#minimal-example ?
