### ISSUE TITLE
CI: code formatting with black

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#185]
would be nice to include it: https://github.com/ambv/black as part of PR acceptance checks (`--check` option

**Comment by matthewfeickert** [comment]
Yes! I am so happy to hear you suggest this as it has been something on my mind as well. Black is really nice. :)

**Comment by matthewfeickert** [comment]
This is just a reminder to myself to implement this soon (probably next week) to make code review easier for all of us. Also we get to add the black badge to the README. [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/ambv/black) :slightly_smiling_face:

**Comment by matthewfeickert** [comment]
Assuming that people are on board with this, and agree with me that ensuring we all have the code style will be good in the long run for having the diffs _really_ only be about the code and not our individual style, I have our first potentially contentious discussion point: single quotes or double quotes?

Black by default uses double quotes and [there is a _long_ Issue there discussing this](https://github.com/ambv/black/issues/118) which was [resolved](https://github.com/ambv/black/issues/118#issuecomment-393298377) (somewhat recently) with the addition of the `--skip-string-normalization` option.

Do we want to go full Black and swap to using double quotes everywhere? I'd prefer not to, and to keep single quotes with `skip-string-normalization = true` in the `pyproject.toml`. Thoughts though?

**Comment by kratsg** [comment]
> Do we want to go full Black and swap to using double quotes everywhere? I'd prefer not to, and to keep single quotes with `skip-string-normalization = true` in the `pyproject.toml`. Thoughts though?

I switch back and forth way too often to really know if I have some innate preference.

**Comment by matthewfeickert** [comment]
Oh, I guess as long as we continue to support Python 2.7 we also need to use `--skip-numeric-underscore-normalization` as Black by default imposes [PEP 515](https://www.python.org/dev/peps/pep-0515/).
