### ISSUE TITLE
workspace JSON?

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#203]
# Description

The main JSON with which the Model gets initialized is a subset of the JSON returned by `readxml`. This is because the XMl defiens not only the pdf but also additional things. In particular it also defines the data (which is not part of the pdf, but one of its arguments).

The output of `readxml` currently does not have a name.

in the spirit of `hist2workspace`, which takes the xml to a `RooWorkspace`,  the output of `xml2json` could be named a 'workspace' spec, which e.g. also defines poi names (`sigxsecoversm` vs `mu`) etc. I don't think in the beginning we need to have compatibility with RooWorkspaces, since they are very featureful. 

We'd need a new JSON schema for that.

**Comment by kratsg** [comment]
We can possibly just expand the `spec.json` to incorporate the extra options. Right now, it's very strictful - but this could be relaxed to allow for the `readxml` case. One could also simply make another schema, call it `workspace.json` which has the schema for the extra properties and imports the `spec.json`.

**Comment by lukasheinrich** [comment]
yeah I was thinking the latter e.g. something like

```
properties:
    pdf: {type: $ref/pdfspec.json}
    measurements: ...
```

I like the idea of retaining a spec for the pdf itself.

**Comment by kratsg** [comment]
Done with #440.
