### ISSUE TITLE
github has officially supported templates -- set them up

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#211]
# Description

https://github.com/diana-hep/pyhf/issues/templates/edit

maybe something for @matthewfeickert since he set up the existing ones

**Comment by matthewfeickert** [comment]
That's really slick! Thanks for bringing this up. I'll look into what's actually going on and then edit our templates to get them going. :+1:

**Comment by kratsg** [comment]
<img width="779" alt="screenshot 2018-08-25 17 02 29" src="https://user-images.githubusercontent.com/761483/44623629-aca03800-a888-11e8-969a-4549b672e09d.png">
