### ISSUE TITLE
Add check for Hello World in README

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#214]
I just realized that I don't think that we actually have a check anywhere for the ["Hello World" example](https://github.com/diana-hep/pyhf#hello-world) that is in the README. 

```
>>> import pyhf
>>> import pyhf.simplemodels
>>> p = pyhf.simplemodels.hepdata_like(signal_data=[12.,11.], bkg_data=[50.,52.], bkg_uncerts=[3.,7.])
>>> *_, CLs_obs,CLs_exp = pyhf.runOnePoint(1.0, [51, 48] + p.config.auxdata, p)
>>> print('obs: {} exp: {}'.format(CLs_obs, CLs_exp[2]))
obs: [0.05290116] exp: [0.06445521]
```

If something was going to break the README example it would break elsewhere as well, but we wouldn't also realize that we need to update the README example. For example, the above should now be [`pyhf.utils.runOnePoint`](https://github.com/diana-hep/pyhf/blob/75e321eda4d50bbcb6e04b690bdb9880da6857eb/pyhf/utils.py#L117).

Unless there is an alternative suggestion I'll open a PR that will add a notebook to both the CI and to the docs.

**Comment by kratsg** [comment]
Doctesting should catch it if we add the readme in.

**Comment by matthewfeickert** [comment]
Ah, okay I'll add that in the PR. I didn't know that it could also get the README, but it is just another file (so duh yeah it can).
