### ISSUE TITLE
clean up name/signature of `runOnePoint`

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#220]
# Description

The signauture of `runOnePoint` is too complicated for newcomers. mostly people are only interested in CLs obs/exp. 

### Describe the solution you'd like

We could use the appraoch used in scikit of a signature that is *iteratively discoverable*

sucht that 

```
clsobs = pyhf.utils.cls(...)
clsobs, clsexp = pyhf.utils.cls(..., return_exp = True) #returns only two numbers
clsobs, clsexpset = pyhf.utils.cls(..., return_expset = True) #returns full 'brazil-band'
clsobs, clsexpset, qvals = pyhf.utils.cls(..., return_expset = True, return_teststatistics = True) #returns full 'brazil-band'  + test statistic values  
```

**Comment by matthewfeickert** [comment]
I very much like this idea.

**Comment by matthewfeickert** [comment]
As `runOnePoint` [currently returns](https://github.com/diana-hep/pyhf/blob/3f03d123f2cc81bf1693d0a4c55e3baa0e23c25d/pyhf/utils.py#L175) `qmu_v, qmuA_v, CLsb, CLb, CLs, CLs_exp` then would we also need to add in a `cls_obs_set` if people want `CLs, CLsb, CLb`?

```
cls_obs = pyhf.utils.cls(...)
cls_obs, cls_exp = pyhf.utils.cls(..., exp = True) #returns only two numbers
cls_obs, cls_exp_set = pyhf.utils.cls(..., exp_set = True) #returns full 'brazil-band'
cls_obs_set, cls_exp_set = pyhf.utils.cls(..., obs_set = True, exp_set = True) #returns CLs, CLsb, CLb, and full 'brazil-band'
cls_obs, cls_exp_set, qvals = pyhf.utils.cls(..., exp_set = True, test_statistics = True) #returns full 'brazil-band'  + test statistic values
```

**Comment by matthewfeickert** [comment]
> We could use the approach used in scikit of a signature that is _iteratively discoverable_

@lukasheinrich can you point me to an example in the docs of how they show the multiple returns in the docstring?

**Comment by lukasheinrich** [comment]
the GP stuff in scikit uses this for example:
http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#sklearn.gaussian_process.GaussianProcessRegressor.predict
