### ISSUE TITLE
Remove Docker Build Status from README

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#244]
Given the discussion in Issue #239 the Docker Hub build will always fail. I would prefer to have it be removed instead of be shown to be failing, as I think it sends the wrong message. The Docker image still gets built properly, just by Docker Cloud, not Docker Hub.

**Comment by kratsg** [comment]
Is there an equivalent cloud.docker.com shields.io badge?

**Comment by matthewfeickert** [comment]
Maybe @lukasheinrich would know? I don't think so though, as things get deployed to Docker Hub and in our particular case the Docker Cloud is private, so I doubt there is a public API for it.

**Comment by matthewfeickert** [comment]
@kratsg Also, is there an easy way to fix the [What does it support](https://diana-hep.org/pyhf/#what-does-it-support) section (specifically the links)?

**Comment by kratsg** [comment]
Probably just don't use the ``uproot`` thing and instead unquote it, and it should render fine.  rST doesn't support checkboxes iirc.

**Comment by matthewfeickert** [comment]
> rST doesn't support checkboxes iirc.

:cry:
