### ISSUE TITLE
add interp code for modifiers (generic labels infrastructure?)

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#246]
# Description

some modifiers implement their modification as an interpolation between user-provided data (e.g. `histosys` and `normsys`). As these computations are typically expensive we want to vectorize these as much as possible #231 (even across multiple modifiers -- the meta-modifier idea). To do this we need a way to group these computations by e.g. interpolation type. 

comment:
This is not a generic property of modifiers and we are now adding more and more decorators to them (`is_constrained`, `pdf_type`, `interp_code`..) so maybe at some point we might consider a generic `labels` key-value infrastructure instead of adding properties one by one

**Comment by kratsg** [comment]
Given the way #285 is going -- this is going to be slowly irrelevant as we've moved the interpolation into the `paramset` labeling and other properties like `is_constrained` will be going away -- and overall, the modifier decorator is most likely going to disappear.
