### ISSUE TITLE
Find better Poisson approximation in ML backends

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#267]
# Description

As I forgot in Issue #266, the different backends have different approximations of the the Poisson distribution. In the [NumPy backend](https://github.com/diana-hep/pyhf/blob/725aa63e091aa59f2fb260580c3b0fb72abb60e4/pyhf/tensor/numpy_backend.py#L159-L163) a Gamma function based approximation is used. However, in the [TensorFlow](https://github.com/diana-hep/pyhf/blob/725aa63e091aa59f2fb260580c3b0fb72abb60e4/pyhf/tensor/tensorflow_backend.py#L198-L200), [PyTorch](https://github.com/diana-hep/pyhf/blob/725aa63e091aa59f2fb260580c3b0fb72abb60e4/pyhf/tensor/pytorch_backend.py#L171-L172), and [MXNet](https://github.com/diana-hep/pyhf/blob/725aa63e091aa59f2fb260580c3b0fb72abb60e4/pyhf/tensor/mxnet_backend.py#L344-L358) backends a Normal function approximation is used.

It would be good if possible to try and have a better approximation than the Normal approximation that is more consistent across backends. I forgot this, and so it won't be obvious to new users.

**Comment by lukasheinrich** [comment]
many backends support pdf distributions. The only possile issue is that poisson is nominally a discrete pdf. but iirc, most backends should already use a continuous approximation of it anyways.
