### ISSUE TITLE
HistoSys and OverallSys with shared nuisance parameters are not supported

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#275]
# Description

In the case we added here #272 `roohf` allows multiple modifiers of different *type* to share the same  nuisance paramerers. We need to support this, and in principle it's is not a big issue. For it we need to 

* [ ] decouple constraint pdfs from modifiers
* [ ] deprecate `qualify_names`

similar to how samples can subscribe to modifiers and many samples can hook into the same modifier, modifiers can subscribe to constraint terms, where many modifiers hook into the same constraint terms.

Some checking needs to occur because not all modifiers can work with all constraint terms

**Comment by kratsg** [comment]
Also additionally deprecate `qualify_names` as well.

**Comment by kratsg** [comment]
Done with #354 and #358.
