### ISSUE TITLE
Bug Report: Benchmark tests are broken on master

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#278]
# Description

PR #276 caused the benchmark tests to fail. This seems to be tied to changes in the `conftest.py`.

# Steps to Reproduce

[Travis CI log](https://travis-ci.org/diana-hep/pyhf/jobs/430857028)

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
@kratsg I won't have time to look at this until the evening, so as you wrote the PR and probably still have the changes mentally cached if you have time to look at this it could be helpful.

**Comment by kratsg** [comment]
Fixed in #268.
