### ISSUE TITLE
Default "shapes" for precomputation

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#288]
# Description

In order to get the default shapes for precomputation, I decided to set the default alphasets shape to `(0,0)` [which is unrealistic anyway]. In all backends except pytorch -- the `ones` and `zeros` return arrays of that particular shape.

# Expected Behavior

I expect pytorch to return an array of the same shape that I fed it.

# Actual Behavior

```python
(Pdb) tensorlib.ones((1,1)).shape
torch.Size([1, 1])
(Pdb) tensorlib.ones((0,0)).shape
torch.Size([0])
```

# Steps to Reproduce

Set up the pytorch backend, and call `pyhf.tensorlib` to see the different behavior. This seems like an interesting regression/edge-case.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
@kratsg I think this has been solved by PR #413, given this is what I now get.

```
>>> import pyhf
>>> pyhf.set_backend(pyhf.tensor.pytorch_backend())
>>> tb = pyhf.tensorlib
>>> tb
<pyhf.tensor.pytorch_backend.pytorch_backend object at 0x7f4ef51b6128>
>>> tb.ones((1,1)).shape
torch.Size([1, 1])
>>> tb.ones((0,0)).shape
torch.Size([0, 0])
```

We should add a test though.

**Comment by kratsg** [comment]
#413 fixes it. Let's add a test to close this issue.

**Comment by matthewfeickert** [comment]
Agreed
