### ISSUE TITLE
Add README to PyPI

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#292]
# Description

At the moment we have no README for the [PyPI page](https://pypi.org/project/pyhf/0.0.15/). The addition of one would be a nice touch (even though I assume that most users will discover the project through GitHub).

**Comment by matthewfeickert** [comment]
Note to self (as I've assigned this to myself): Use [`twine` to make sure that the README renders correctly.](https://pythonbytes.fm/episodes/show/97/java-goes-paid). It might be worth making this part of the set of tests.

**Comment by matthewfeickert** [comment]
@lukasheinrich Related to this, how did you first deploy to PyPI? Did you use `twine` and then something like

```
python setup.py sdist bdist_wheel
twine upload dist/*
```

I ask only so that I know what stuff needs to go into PR #338.

**Comment by lukasheinrich** [comment]
I think I just did `python setup.py sdist upload`

**Comment by matthewfeickert** [comment]
The [PyPA apparently doesn't recommend that anymore](https://packaging.python.org/guides/distributing-packages-using-setuptools/#uploading-your-project-to-pypi).

It obviously hasn't mattered, but do you know what would be necessary to switch how the deployment happens with Travis so we can start distributing wheels as well? That can be a separate PR if that makes more sense.

**Comment by lukasheinrich** [comment]
does the way travis does deployment depend on how it was initially deploted?

**Comment by matthewfeickert** [comment]
> does the way travis does deployment depend on how it was initially deployed?

No, I was confused by some blogs. As you pointed out [wheels need to be added to the Travis YAML](https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions).
