### ISSUE TITLE
JSON schema validation failure when loading Model with dummy spec

### ISSUE THREAD

**Issue by dantrim** [diana-hep/pyhf#327]
# Description

I am not entirely sure what is incorrect with a dummy spec that I have created for loading into a Model. I attempted using first a JSON spec created from loading in my HistFactory XMLs and then ended up whittling it back down to a dummy spec with as few things as possible and then went back to creating a python dictionary OTF within some test code.

# Expected Behavior

That the Model can get loaded with the input python dictionary.

# Actual Behavior

A lot of terrible looking JSON schema validation which is difficult to use to pin point at what point in the JSON file the error is located.

# Steps to Reproduce

```bash
git clone -b master https://github.com/diana-hep/pyhf.git
cd pyhf/
export PYTHONPATH=${PWD}:${PYTHONPATH}
cd ..
python test_schema.py
```
where `test_schema.py` is attached. The output I see is also attached as "failure.log". 

[failure.log.zip](https://github.com/diana-hep/pyhf/files/2496349/failure.log.zip)
[test_schema.py.zip](https://github.com/diana-hep/pyhf/files/2496347/test_schema.py.zip)

**Comment by dantrim** [comment]
Thanks @kratsg that worked for my example there (I had made a copy & paste error based on the example notebook where it passes `source['channels']` but source in that case is not a model spec). However, when I now use the JSON created by `readxml` from a full HistFitter workspace I get a similar problem. There are 30 NP and ~6 samples with a couple of control regions so understanding the output is a bit more challenging...

The JSON model spec created by is attached (wwbb_config_full.json.zip).

[wwbb_config_full.json.zip](https://github.com/diana-hep/pyhf/files/2496503/wwbb_config_full.json.zip)

**Comment by kratsg** [comment]
Well, the JSON created by readxml contains a `toplvl`, so what you need to do is something like the command-line interface we provide (https://github.com/diana-hep/pyhf/blob/master/pyhf/commandline.py#L51-L91). But to simplify it, your procedure is something like

```python
    parsed_xml = pyhf.readxml.parse('validation/xmlimport_input2/config/example.xml',
                                    'validation/xmlimport_input2')
    spec = {'channels': parsed_xml['channels']}
    pdf = pyhf.Model(spec, poiname='SigXsecOverSM')
```

as taken from https://github.com/diana-hep/pyhf/blob/master/tests/test_import.py#L54-L69.

**Comment by kratsg** [comment]
This is something we do need to improve on as things are slightly separated.
