### ISSUE TITLE
Fix CLs math mode display in Hello World example

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#351]
# Description

In the Hello World example Jupyter notebook I mistakenly used the Sphinx math mode syntax in the Markdown cells:

```
 :math:`CL_{s}`
```

However, this doesn't get rendered right for some reason on the webpage. Instead, I should probably just use Jupyter's native LaTeX inline mathmode

```
$\mathrm{CL}_{s}$
```

**Comment by kratsg** [comment]
That should be `$\mathrm{CL}_{s}$`

**Comment by matthewfeickert** [comment]
Yes. Indeed it should, especially as I use that in other place. Need more :coffee: today apparently.

**Comment by matthewfeickert** [comment]
Hm, [currently the Hello World notebook](https://github.com/diana-hep/pyhf/blob/7e3044e51cfc6f04167c91bf8d48315399c0eb75/docs/examples/notebooks/hello-world.ipynb) is just using normal mathmode but it is getting rendered out in Sphinx as the `:math:` environment tag rather then a rendered equation.

**Notebook:**
```latex
**Returning the observed $CL_{s}$, $CL_{s+b}$, and $CL_{b}$**
```

**Sphinx:**
![sphinx_mathmode](https://user-images.githubusercontent.com/5142394/47763801-2e994c80-dc90-11e8-952d-dbcd043dde91.png)

I'm not sure how to fix that.

**Comment by kratsg** [comment]
https://nbsphinx.readthedocs.io/en/0.2.2/example.html and https://github.com/spatialaudio/nbsphinx/blob/master/doc/markdown-cells.ipynb
