### ISSUE TITLE
consolidation: add simplemodls to __all__

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#359]
# Description

It would be nice if the snippet in the README could be shorter:

right now this is needed
```
import pyhf
import pyhf.simplemodels
pdf = pyhf.simplemodels.hepdata_like(signal_data=[12.0], bkg_data=[50.0], bkg_uncerts=[3.0])
CLs_obs = pyhf.utils.hypotest(1.0, [51] + pdf.config.auxdata, pdf)
```

whereas if we pre-import `simplemodels` it could be 
```
import pyhf
pdf = pyhf.simplemodels.hepdata_like(signal_data=[12.0], bkg_data=[50.0], bkg_uncerts=[3.0])
CLs_obs = pyhf.utils.hypotest(1.0, [51] + pdf.config.auxdata, pdf)
```

since `simplemodels.py` doesn't add much code, i don't think it would slow down things a lot

**Comment by kratsg** [comment]
> since `simplemodels.py` doesn't add much code, i don't think it would slow down things a lot

We have a test that measures how long it takes to import `pyhf`. So we can make the change in a PR and see if tests pass :)
