### ISSUE TITLE
Binder builds image but fails at launch

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#389]
# Description

I've noticed that with recent Binder builds if you actually try to run [the demo Statistical Analysis notebook](https://mybinder.org/v2/gh/diana-hep/pyhf/master?filepath=docs%2Fexamples%2Fnotebooks%2Fbinderexample%2FStatisticalAnalysis.ipynb) that as soon as you run _any_ of the cells it will freeze up and eventually time out with a 

>Connection failed
>A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

box displayed on screen. I [reported this on the jupyterhub/binder Gitter](https://gitter.im/jupyterhub/binder?at=5c38258f6a394e28218ca9de) and @betatim and @minrk very helpfully gave some feedback. Tim was able to get [the stdout for when the Binder is launched](https://gist.github.com/betatim/b0ea8292c7725e3e8e26b03d6cc45101). The following suggestions were made:

- Pinning `ipython<7` [could be problematic as](https://gitter.im/jupyterhub/binder?at=5c38c9a966f3433023b0053f): 
> Pinning IPython but not Jupyter console is now introducing the same problem that pinning IPython was meant to solve. Now console requires pt 2, while IPython is pinned to a version that requires pt 1.
I’d recommend against depending on the Jupyter metapackage. It’s a big thing that includes stuff like the qtconsole. Instead, I’d depend directly on the packages you actually use (unless that actually includes all the Jupyter frontends)
- In [`postBuild`](https://github.com/diana-hep/pyhf/blob/f9b833c1c7cf0cafd87e23f84f6c815fe50b3047/binder/postBuild) it probably [doesn't make sense to have both the `--ignore-installed` and `--upgrade` option flags for Binder](https://gitter.im/jupyterhub/binder?at=5c38af3e2e25e453d7662b05):
> My initial inclination would be the `--ignore-installed` flag to pip, which is explicitly requesting a mixture of multiple versions of libraries to be installed, including all dependencies already in the env. `upgrade` and `ignore-installed` are rarely used together. 

>Likely only upgrade is desired.

This needs to get debugged and why things fail should also be interesting to learn.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
I noticed this last night too!

**Comment by matthewfeickert** [comment]
Good news: Benjamin knows his stuff and removing `--ignore-installed` in `postBuild` fixes it. :tada: 

I'm saying "fixes it" because I started a build off of this branch and the notebook works again: [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/diana-hep/pyhf/fix/get-Binder-images-to-not-fail-at-launch?filepath=docs%2Fexamples%2Fnotebooks%2Fbinderexample%2FStatisticalAnalysis.ipynb)

**Comment by matthewfeickert** [comment]
Perhaps still worth looking into if `ipython<7` is actually required or not.
