### ISSUE TITLE
Pin optional dependencies at the minor release level

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#397]
# Description

To avoid having our prior releases break like `v0.0.15` did in Issue #396 it would be good to pin our optional dependencies at the minor release level for each release. This should safeguard us from old releases getting broken by API changes in the dependencies that we use as applications.

To be clear, I don't think we should limit the dependencies in `install_requires` beyond placing _lower_ bounds, but I do think that we should now be placing upper bounds on all of the optional dependencies as we are really more using those as **applications** in our library.

**Comment by matthewfeickert** [comment]
This should also make the CI more robust so that we don't have to drop everything and do CI debugging as often.

**Comment by matthewfeickert** [comment]
@lukasheinrich We had a discussion about this a while ago on Skype and if I remember correctly @kratsg had suggested that we **not** pin at minor versions, but just use [PEP 508](https://www.python.org/dev/peps/pep-0508/)'s compatible release syntax to allow for minor version updates while keeping the major version pinned (and assuming that all of our dependencies treat API breaking changes as being acceptable to release only in major versions).

Do I remember this correctly, and if so, then does this seem fine to both of you? e.g.,

https://github.com/diana-hep/pyhf/blob/ee6668c42501c78a32fde8d99a8c3b326c57d5c4/setup.py#L15

becoming

```
'tensorflow~=1.12.0'
```

?

**Comment by kratsg** [comment]
This is fine to me. We can also use a clever idea to unpin some versions and check if the next major release is compatible with `pyhf` as well.

**Comment by matthewfeickert** [comment]
> We can also use a clever idea to unpin some versions and check if the next major release is compatible with pyhf as well.

Yes, this was one of the motivations for this Issue being created in the first place. The compatible release syntactic sugar from PEP 508 just makes this very easy to test. :)
