### ISSUE TITLE
Use Xenial build environment as default on Travis CI

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#417]
# Description

If we change to using [Xenial](https://docs.travis-ci.com/user/reference/xenial/) as the default build environment on Travis we get some speedup as compared to [Trusty](https://docs.travis-ci.com/user/reference/trusty).

Comparing [this build on `master`](https://travis-ci.org/diana-hep/pyhf/builds/502239716) using Trusty to [this build using Xenial](https://travis-ci.org/diana-hep/pyhf/builds/502303475)

| `Trusty` | `Xenial` |
|----------|----------|
| ![master_build_time](https://user-images.githubusercontent.com/5142394/53848584-83204180-3f7a-11e9-935e-e584367c757b.png) | ![xenial_build_time](https://user-images.githubusercontent.com/5142394/53848610-9d5a1f80-3f7a-11e9-88aa-32a834c51bee.png) |

we save a substantial amount of time in the full test suite that runs on `master`. I would suggest that we switch over to having Xenial be the default.

**Comment by matthewfeickert** [comment]
@lukasheinrich @kratsg If you agree then I have a branch ready to go for a PR.

**Comment by matthewfeickert** [comment]
@lukasheinrich @kratsg pinging on this for thoughts.

**Comment by kratsg** [comment]
If we get a speed up -- then switch.
