### ISSUE TITLE
Add codefactor.io badge

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#421]
# Description

CodeFactor provides an overall code-grade which might be useful to have? https://www.codefactor.io/

**Comment by lukasheinrich** [comment]
we apparently get a A-

[![CodeFactor](https://www.codefactor.io/repository/github/diana-hep/pyhf/badge)](https://www.codefactor.io/repository/github/diana-hep/pyhf)

**Comment by matthewfeickert** [comment]
That seems pretty great given that we get an A- with two F's in [the summary report](https://www.codefactor.io/repository/github/diana-hep/pyhf).
