### ISSUE TITLE
add versioning to schema

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#451]
# Description

For future-proofing we need to add versioning to the schemas. I would propose that we have a simple string-based version

```
version: "1.0"
.. remaining keys possibly version specific ..
```

and the following strategy

* when loading the model, it is validated against schemas of the declared version. 

* within the code, a given in-memory representation i.e. the `Workspace` class can be 
instantiated using specs of a subrange of versions `[v_min,v_max]`. possible the ctor will forward/backward evolve to a common format ( I suspect usually forward, i.e. accept a v1 representation but convert it into a v2 representations internally

* a given `pyhf` version  can read a subset of pyhf schema versions. The goal here should be to be as backward and forwards compatible as possible
  * forward compatible: validating the version number itself should be optional (i.e. a v2 spec might be structurally compatible with v1, e.g. if we add new optional fields) so it should still validate as a v1 model even though it has "version: v2" in the spec.
  * backward compatible: future pyhf versions should carry all older schemas as well so older models can be validated. if needed we will add converters for forward evolution to a more recent version once a model is validated in a older version
  * probably would be nice to have `pyhf` be able to output what version range is supported
  * to the extend that pyhf has translators from one version to another, a cli to do this conversion might be nice in order to normalize let's say multiple worksapces defined in different versions for a combination 

* if backward compatibility is not possible, this means a older version of the spec can only be read in a older version of pyhf. This is fine per se, this necessarily will require a new major release, but we should really try to avoid it.

**Comment by kratsg** [comment]
I have a couple of thoughts on this. Given that the spec loading is simply to flesh out the workspace/model - perhaps we can move the Workspace class into a versioned piece of python code -- but this means adding tests and ensuring all the various forward/backward compatibilities that come with it.

I'm ok with versioning the schema alone - but we really should not be changing it too much after this point in time to be honest -- since we're already able to round-trip results.

**Comment by lukasheinrich** [comment]
yes I don't expect backward-incompatible changes math-wise, but could imagine that we move things around in the schema to accomodate future features. Given the first point I think the chance that we can forward translate old schemas is quite high since I don't think we'll drop any features.

**Comment by kratsg** [comment]
> yes I don't expect backward-incompatible changes math-wise, but could imagine that we move things around in the schema to accomodate future features. Given the first point I think the chance that we can forward translate old schemas is quite high since I don't think we'll drop any features.

It's a good point. This is the part that I'm still thinking about how we can structure things. One can version explicitly -- or we could keep around older versions:

```
- pyhf/schemas/latest/ --> v2/
- pyhf/schemas/v1/
- pyhf/schemas/v2/
```

as an example of versioning implicitly. Then we're keeping around all versions of it. Similarly, if one does it this way, then we can just provide helper utilities to convert from one version to another.

Similarly, if we version explicitly, with the version number, we can write a utility that handles the conversions entirely.
