### ISSUE TITLE
Bug: pyhf --help requires uproot and so fails if installed without

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#466]
# Description

The installation of `pyhf` without the [`pyhf[xmlio]` option](https://github.com/diana-hep/pyhf/blob/1187a672c0283144f76cd869bfdef78f0b80006f/setup.py#L25) or `pyhf[complete]` does not install `uproot` as a dependency. However, `pyhf --help` tries to load `uproot` and fails without it being present.

A check should either be made for the existence and options skipped if `uproot` isn't installed, or `uproot` should be added as a core dependency.

# Expected Behavior

```
$ pip install pyhf
$ pyhf --help
Usage: pyhf [OPTIONS] COMMAND [ARGS]...

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  cls
  json2xml
  xml2json  Entrypoint XML: The top-level XML file for the PDF definition.
```

# Actual Behavior

```
$ pip install pyhf
$ pyhf --help
Traceback (most recent call last):
  File "/home/docker/.local/bin/pyhf", line 6, in <module>
    from pyhf.commandline import pyhf
  File "/home/docker/.local/lib/python3.6/site-packages/pyhf/commandline.py", line 7, in <module>
    from . import writexml
  File "/home/docker/.local/lib/python3.6/site-packages/pyhf/writexml.py", line 8, in <module>
    import uproot
ModuleNotFoundError: No module named 'uproot'
```

# Steps to Reproduce

See above

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
I have deja vu: #441

**Comment by kratsg** [comment]
Actually, this isn't a bug in master. it might be a bug in the last release. This works as expected.

**Comment by matthewfeickert** [comment]
> Actually, this isn't a bug in master. it might be a bug in the last release.

Ah @kratsg you're right. The last PyPI release was [`v0.1.0` on 2019-04-13](https://pypi.org/project/pyhf/0.1.0/) but PR #444 was merged in on 2019-04-15. So you're right that this isn't a bug in `master`, but I think that we should still leave this open until we release `v0.1.1` as a user will still experience this.
