### ISSUE TITLE
data specification for workspace is not specific enough

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#474]
# Description

Related to #106.  https://github.com/diana-hep/pyhf/blob/master/pyhf/schemas/1.0.0/workspace.json#L8 currently describes data as an object, but that could be anything. We probably want to specify it as an object with keys for example... or perhaps as @lukasheinrich stated before, an array of items.

**Comment by matthewfeickert** [comment]
To ping this given some recent discussion, it seems that there is consensus to use an array of items. :+1: The idea is that it is easier to inject things into a fixed order list than to inject by key name (which won't be known until look up). @kratsg gave the example that

> ... `workspace.json/data/0/rates` is easier than `workspace.json/data/SRA_lowmeff`
