### ISSUE TITLE
Consider use of src directory for project directory structure

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#512]
# Description

There is no pressing issue here, but I would like to suggest the idea and have some discussion of moving to using the `src` directory pattern.

Instead of trying to summarize here why I think this should be the case I will let others do so for me:
- PythonBytes [Episode #22 show notes: "Item 5: Python Package src-ery"](https://pythonbytes.fm/episodes/show/22/pythonpath-considered-harmful)
   - [Full transcript of episode](https://pythonbytes.fm/episodes/transcript/22/pythonpath-considered-harmful)
   - pytest's [recommendation for projects that have a `__init__.py` in the `tests` directory](https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules)
   - Ionel Mărieș's argument in his "[Packaging a python library](https://blog.ionelmc.ro/2014/05/25/python-packaging/)" blog post on the subject
- Hynek Schlawack's "[Testing & Packaging](https://hynek.me/articles/testing-packaging/)" blog post
- The PyPA's [summary of their recommendations given their 2019 Packaging Mini Summit](https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983)

This isn't an argument, but more libraries are starting to adopt `src` (though to be fair, many do not). A few I know off the top of my head are:
   - [pytest](https://github.com/pytest-dev/pytest)
   - [pyramid](https://github.com/pylons/pyramid)
   - [hypothesis-jsonschema](https://github.com/Zac-HD/hypothesis-jsonschema)

**Comment by lukasheinrich** [comment]
I'm sympathetic

**Comment by matthewfeickert** [comment]
If you two are on board with this I have a branch with this already changed that passes the CI (the only thing I would have questions on are how the schemas need to be updated as I'm a bit confused on the path requirements of PR #481 and #452).

**Comment by kratsg** [comment]
where's the PR?

**Comment by matthewfeickert** [comment]
> where's the PR?

I haven't opened one, as it seemed pointless if you both were very not in favor. What are your thoughts?

**Comment by lukasheinrich** [comment]
let's do it
