### ISSUE TITLE
Make Issue and Pull Request Templates

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#57]
Having uniform templates for feature requests, bug reports, feature additions, and bug patches will make things easier for maintainers to parse and organize quickly.

**Comment by matthewfeickert** [comment]
@lukasheinrich from some trial and error in a test repo and [from this Issue](https://github.com/RichardLitt/knowledge/issues/9#issue-248018426) it looks like the "multiple" template support is pretty neutered in that you need to actually know what templates exist already and access them from an API in the URL.

I can either just create single templates that encourage the user to delete the sections they don't want to use in the Issue/PR, or I can create templates that ask the user to click the "Preview" button to render the MD and then there will be links to the relevant template they want. Thoughts on what would be the best (as we'll be the ones seeing them the most for some time)?

**Comment by lukasheinrich** [comment]
thanks for looking into this @matthewfeickert. I think if we just go with the templates github natively understands we should already be good

**Comment by matthewfeickert** [comment]
Closed by PRs #87 and #89
