### ISSUE TITLE
create proper test fixtures

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#66]
Many of the tests have large blocks of setup code that could be shared as proper `@pytest.fixtures` 

https://docs.pytest.org/en/latest/fixture.html

**Comment by matthewfeickert** [comment]
@lukasheinrich Can you elaborate a bit more on which tests would benefit from pytest fixtures? It is obvious that `test_optim.py` benefits from this (the tests can just be reduced to one parameterized fixture), however for `test_validation.py` it seems a bit less clear. Given that each test there is relying on a different `source` and the `spec` in each test is changing as well fixtures would need to be scoped at the `function` level. At that point I don't think (?) that using fixtures provides any benefit over just defining normal functions.

I might be misunderstanding something though.
