### ISSUE TITLE
write documentation

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#76]
in yadage, we have a travis deploy job that automatically builds docs and pushes to gh-pages

https://github.com/diana-hep/yadage/blob/master/.travis.yml#L25

- [x] Setup CI
- [x] Add automodule in order to get source docs 
- [x] Setup theme that supports Google Style docstrings

**Comment by matthewfeickert** [comment]
@lukasheinrich I don't know how much of a hassle it would be to change Sphinx themes, but I think it would be really nice if we could adopt a Sphinx theme that allowed for [Google Style docstrings](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google). To my mind they are much more readable while looking at the actual code, which is a plus.

As an example, PyTorch uses them with the [Read The Docs Sphinx theme](https://github.com/rtfd/sphinx_rtd_theme). So their docstrings (like this one for [`torch.distributions.bernoulli`](http://pytorch.org/docs/master/_modules/torch/distributions/bernoulli.html#Bernoulli)) end up looking [like this when rendered](http://pytorch.org/docs/master/distributions.html#bernoulli).

If this sounds feasible it looks like we could either use [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme) or [napoleon](https://bitbucket.org/RobRuana/sphinx-contrib). Thoughts?

**Comment by lukasheinrich** [comment]
ok so a stub is live here: diana-hep.github.io/pyhf now we just need to fill it with some content my editing the files under docs/source

**Comment by matthewfeickert** [comment]
@lukasheinrich Great! Cool to see the start of the docs!

**Comment by matthewfeickert** [comment]
> but I think it would be really nice if we could adopt a Sphinx theme that allowed for Google Style docstrings.

Based off of @kratsg's [comment in PR #157](https://github.com/diana-hep/pyhf/pull/157#issuecomment-386888086)

> This isn't theme-dependent. That's just a functionality baked into Sphinx itself.

This should be possible.

**Comment by kratsg** [comment]
I'll add an example of this in the PR so it's there to work off of.

**Comment by kratsg** [comment]
> I'll add an example of this in the PR so it's there to work off of.
done

**Comment by matthewfeickert** [comment]
Closing this given the above.
