### ISSUE TITLE
autograd for numpy backend?

### ISSUE THREAD

**Issue by cranmer** [diana-hep/pyhf#79]
https://github.com/HIPS/autograd

**Comment by cranmer** [comment]
FYI: @matthewfeickert @kratsg

**Comment by matthewfeickert** [comment]
I am in the process of finishing #86, but once that is done I will start on this if @kratsg doesn't beat me to it.

**Comment by kratsg** [comment]
you probably will beat me to it. @cranmer do you know if they implement runge-kutta or something else? It looked like runge-kutta from a first glance.

**Comment by cranmer** [comment]
That tools is just providing the autodiff as far as I know. They have some examples that do various things with those derivatives, but I don't think they are focusing on providing minimization. They do have adam and rmsprop:

https://github.com/HIPS/autograd/blob/master/autograd/misc/optimizers.py

Probably would be best to do Newton's method to be comparable to the other backends, just use autograd for the derivatives

**Comment by matthewfeickert** [comment]
Given that a contributor to autograd has [suggested that people check out JAX](https://github.com/HIPS/autograd/issues/46#issuecomment-475910293) I think it is safe to say that this Issue can be closed as Issue #416 will cover it.
