### ISSUE TITLE
implement sampling from pdf

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#98]
# Description

We would like to be able to sample from the pdf. For that we need to

1. sample values for auxiliary measurements 
2. based on aux data, derive poisson rate parameters
3. sample from poissons

e.g.

```
pdf = pyhf.pdf(...)
data  = pdf.sample()
```

**Comment by matthewfeickert** [comment]
@lukasheinrich Given PR #108, we should also probably check out [TensorFlow Probability](https://github.com/tensorflow/probability), which [made its public release today](https://medium.com/tensorflow/introducing-tensorflow-probability-dca4c304e245). (great work, Dustin!)

**Comment by lukasheinrich** [comment]
seeing that is the reason I opened this request :)

**Comment by lukasheinrich** [comment]
closing this in lieu of #109
